version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    groups:
      all-frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/backend/document-reader-service"
    schedule:
      interval: "monthly"
    groups:
      all-backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions-dependencies:
        patterns:
          - "*"
